[identities]
alleymon = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGk9fhwXG95cVD9DLsHuXrdJYs8DsUF/AmYWcO1+bPVd alleymon"

[[paths]]
glob = "secrets/**/*.age"
identities = [ "alleymon" ]

[[paths]]
glob = "config/espanso/match/*.age"
identities = [ "alleymon" ]
